import { useEffect } from 'react';
import '../frontend/styles.css';

export default function App() {
  useEffect(() => {
    // State
    let selectedDay = 17;
    let searchQuery = '';

    // Days data
    const days = [
      { dayName: 'MER', dayNumber: 14 },
      { dayName: 'GIO', dayNumber: 15 },
      { dayName: 'VEN', dayNumber: 16 },
      { dayName: 'SAB', dayNumber: 17 },
      { dayName: 'DOM', dayNumber: 18 },
      { dayName: 'LUN', dayNumber: 19 },
      { dayName: 'MAR', dayNumber: 20 },
    ];

    // Render calendar days
    function renderCalendar() {
      const calendarContainer = document.getElementById('calendarDays');
      if (!calendarContainer) return;

      calendarContainer.innerHTML = '';

      days.forEach(day => {
        const button = document.createElement('button');
        button.className = `day-btn ${selectedDay === day.dayNumber ? 'active' : ''}`;
        button.dataset.dayNumber = String(day.dayNumber);
        
        button.innerHTML = `
          <span class="day-name">${day.dayName}</span>
          <span class="day-number">${day.dayNumber}</span>
          <span class="day-underline"></span>
        `;

        button.addEventListener('click', () => selectDay(day.dayNumber));
        
        calendarContainer.appendChild(button);
      });
    }

    // Select a day
    function selectDay(dayNumber: number) {
      if (selectedDay === dayNumber) return;
      
      selectedDay = dayNumber;
      
      // Update active state
      const allButtons = document.querySelectorAll('.day-btn');
      allButtons.forEach(btn => {
        const btnDayNumber = parseInt((btn as HTMLElement).dataset.dayNumber || '0');
        
        if (btnDayNumber === dayNumber) {
          btn.classList.add('active');
        } else {
          btn.classList.remove('active');
        }
      });
    }

    // Setup event listeners
    function setupEventListeners() {
      const searchInput = document.getElementById('searchInput') as HTMLInputElement;
      
      if (searchInput) {
        searchInput.addEventListener('input', (e) => {
          searchQuery = (e.target as HTMLInputElement).value;
          console.log('Search query:', searchQuery);
        });
      }
    }

    // Initialize
    renderCalendar();
    setupEventListeners();
  }, []);

  return (
    <div className="container">
      <div className="content">
        {/* Header */}
        <div className="header">
          <p className="header-subtitle">Ora al cinema</p>
          <h1 className="header-title">Trova la tua sala</h1>

          {/* Search Bar */}
          <div className="search-bar">
            <svg className="search-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="11" cy="11" r="8"></circle>
              <path d="m21 21-4.35-4.35"></path>
            </svg>
            <input 
              type="text" 
              placeholder="Cerca cinema o film..." 
              className="search-input"
              id="searchInput"
            />
            <button className="location-btn">
              <svg className="location-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"></path>
                <circle cx="12" cy="10" r="3"></circle>
              </svg>
            </button>
            <span className="vo-text">VO</span>
          </div>

          {/* Calendar Days */}
          <div className="calendar-days" id="calendarDays">
            {/* Days will be generated by JavaScript */}
          </div>
        </div>
      </div>
    </div>
  );
}